"""Stable runtime constants grouped by ownership."""

from .requirements import (
    CAPTURE_OLLAMA_BASE_MODEL,
    CAPTURE_OLLAMA_PROFILE_ID,
    OLLAMA_MODEL_REQUIREMENT_ID,
    OLLAMA_RUNTIME_REQUIREMENT_ID,
    REQUIREMENT_IDS,
    WHISPER_REQUIREMENT_ID,
    WINDOWSML_REQUIREMENT_ID,
)
from .versions import (
    API_VERSION,
    CAPTURE_DOCUMENT_SCHEMA_VERSION,
    MAX_RUNTIME_ARTIFACT_BYTES,
    RUNTIME_VERSION,
)

__all__ = [
    "API_VERSION",
    "CAPTURE_DOCUMENT_SCHEMA_VERSION",
    "CAPTURE_OLLAMA_BASE_MODEL",
    "CAPTURE_OLLAMA_PROFILE_ID",
    "MAX_RUNTIME_ARTIFACT_BYTES",
    "OLLAMA_MODEL_REQUIREMENT_ID",
    "OLLAMA_RUNTIME_REQUIREMENT_ID",
    "REQUIREMENT_IDS",
    "RUNTIME_VERSION",
    "WHISPER_REQUIREMENT_ID",
    "WINDOWSML_REQUIREMENT_ID",
]
